### ISSUE TITLE
[Bug]: Monero SideShift & FixedFloat Errors

### ISSUE THREAD

**Issue by vbrekher** [btcpayserver/btcpayserver-plugins#34]
### What is your BTCPay version?

BTCPay Server v1.6.3.0

### How did you deploy BTCPay Server?

[BTCPayServer Google Cloud](https://github.com/btcpayserver/btcpayserver-googlecloud)

### What happened?

SideShift won’t load with XMR as a payment.

<img width="387" alt="Screenshot 2022-07-31 at 23 45 38" src="https://user-images.githubusercontent.com/6142607/182044850-ac0dd460-c704-4806-87e7-ac28bf3ea566.png">

<img width="728" alt="Screenshot 2022-07-31 at 23 45 18" src="https://user-images.githubusercontent.com/6142607/182044846-3b542143-50a3-4e13-bdef-2203207fd7e4.png">

### How did you encounter this bug?

1. Create a payment request 
2. Select XMR as a payment method 
3. Click Pay with SideShift 

### What browser do you use?

Chrome version 104.0.5112.65 (Official Build) beta (x86_64)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by StevenWilliams** [comment]
I'm getting the same error, when using sideshift when BTC (on chain) is selected as the payment method. Selecting BTC lightning does work though.

Here's a test invoice: https://btcpayserver2.stevenw.ca/i/AmDLNvPgw7EJnKq8Tn14Ay
Side Shift Version: 1.0.7.0
BTCPayServer version: 1.6.7

```
Widget.4ea7db75.chunk.js:2 React-Modal: "parentSelector" prop did not returned any DOM element. Make sure that the parent element is unmounted to avoid any memory leaks.
(anonymous) @ Widget.4ea7db75.chunk.js:2
i.removePortal @ Widget.4ea7db75.chunk.js:2
value @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
uc @ Widget.4ea7db75.chunk.js:2
lc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
(anonymous) @ Widget.4ea7db75.chunk.js:2
_u @ Widget.4ea7db75.chunk.js:2
ru @ Widget.4ea7db75.chunk.js:2
w @ Widget.4ea7db75.chunk.js:2
C @ Widget.4ea7db75.chunk.js:2
(anonymous) @ Widget.4ea7db75.chunk.js:2
l @ Widget.4ea7db75.chunk.js:2
n @ Widget.4ea7db75.chunk.js:2
postMessage (async)
r @ Widget.4ea7db75.chunk.js:2
c.setImmediate @ Widget.4ea7db75.chunk.js:2
E @ Widget.4ea7db75.chunk.js:2
C @ Widget.4ea7db75.chunk.js:2
(anonymous) @ Widget.4ea7db75.chunk.js:2
l @ Widget.4ea7db75.chunk.js:2
n @ Widget.4ea7db75.chunk.js:2
postMessage (async)
r @ Widget.4ea7db75.chunk.js:2
c.setImmediate @ Widget.4ea7db75.chunk.js:2
E @ Widget.4ea7db75.chunk.js:2
R @ Widget.4ea7db75.chunk.js:2
t.unstable_scheduleCallback @ Widget.4ea7db75.chunk.js:2
Tu @ Widget.4ea7db75.chunk.js:2
nu @ Widget.4ea7db75.chunk.js:2
Su @ Widget.4ea7db75.chunk.js:2
xu @ Widget.4ea7db75.chunk.js:2
Promise.then (async)
(anonymous) @ Widget.4ea7db75.chunk.js:2
fc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
(anonymous) @ Widget.4ea7db75.chunk.js:2
_u @ Widget.4ea7db75.chunk.js:2
su @ Widget.4ea7db75.chunk.js:2
qi @ Widget.4ea7db75.chunk.js:2
(anonymous) @ Widget.4ea7db75.chunk.js:2
Show 70 more frames
Widget.4ea7db75.chunk.js:2 TypeError: Cannot read properties of undefined (reading 'id')
    at Pt (CreateOrderWidget.5f0d912c.chunk.js:1:122430)
    at _a (Widget.4ea7db75.chunk.js:2:399512)
    at _c (Widget.4ea7db75.chunk.js:2:457011)
    at yu (Widget.4ea7db75.chunk.js:2:445956)
    at bu (Widget.4ea7db75.chunk.js:2:445884)
    at vu (Widget.4ea7db75.chunk.js:2:445747)
    at iu (Widget.4ea7db75.chunk.js:2:442531)
    at ru (Widget.4ea7db75.chunk.js:2:441082)
    at w (Widget.4ea7db75.chunk.js:2:474090)
    at C (Widget.4ea7db75.chunk.js:2:474624)
    at Widget.4ea7db75.chunk.js:2:478058
    at l (Widget.4ea7db75.chunk.js:2:478173)
    at n (Widget.4ea7db75.chunk.js:2:477118)
(anonymous) @ Widget.4ea7db75.chunk.js:2
ss @ Widget.4ea7db75.chunk.js:2
n.callback @ Widget.4ea7db75.chunk.js:2
uo @ Widget.4ea7db75.chunk.js:2
mc @ Widget.4ea7db75.chunk.js:2
bc @ Widget.4ea7db75.chunk.js:2
vc @ Widget.4ea7db75.chunk.js:2
(anonymous) @ Widget.4ea7db75.chunk.js:2
_u @ Widget.4ea7db75.chunk.js:2
ru @ Widget.4ea7db75.chunk.js:2
w @ Widget.4ea7db75.chunk.js:2
C @ Widget.4ea7db75.chunk.js:2
(anonymous) @ Widget.4ea7db75.chunk.js:2
l @ Widget.4ea7db75.chunk.js:2
n @ Widget.4ea7db75.chunk.js:2
postMessage (async)
r @ Widget.4ea7db75.chunk.js:2
c.setImmediate @ Widget.4ea7db75.chunk.js:2
E @ Widget.4ea7db75.chunk.js:2
C @ Widget.4ea7db75.chunk.js:2
(anonymous) @ Widget.4ea7db75.chunk.js:2
l @ Widget.4ea7db75.chunk.js:2
n @ Widget.4ea7db75.chunk.js:2
postMessage (async)
r @ Widget.4ea7db75.chunk.js:2
c.setImmediate @ Widget.4ea7db75.chunk.js:2
E @ Widget.4ea7db75.chunk.js:2
R @ Widget.4ea7db75.chunk.js:2
t.unstable_scheduleCallback @ Widget.4ea7db75.chunk.js:2
Tu @ Widget.4ea7db75.chunk.js:2
nu @ Widget.4ea7db75.chunk.js:2
Su @ Widget.4ea7db75.chunk.js:2
xu @ Widget.4ea7db75.chunk.js:2
Promise.then (async)
(anonymous) @ Widget.4ea7db75.chunk.js:2
fc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
dc @ Widget.4ea7db75.chunk.js:2
pc @ Widget.4ea7db75.chunk.js:2
(anonymous) @ Widget.4ea7db75.chunk.js:2
_u @ Widget.4ea7db75.chunk.js:2
su @ Widget.4ea7db75.chunk.js:2
qi @ Widget.4ea7db75.chunk.js:2
(anonymous) @ Widget.4ea7db75.chunk.js:2
Show 52 more frames
Widget.4ea7db75.chunk.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at Pt (CreateOrderWidget.5f0d912c.chunk.js:1:122430)
    at _a (Widget.4ea7db75.chunk.js:2:399512)
    at _c (Widget.4ea7db75.chunk.js:2:457011)
    at yu (Widget.4ea7db75.chunk.js:2:445956)
    at bu (Widget.4ea7db75.chunk.js:2:445884)
    at vu (Widget.4ea7db75.chunk.js:2:445747)
    at iu (Widget.4ea7db75.chunk.js:2:442531)
    at ru (Widget.4ea7db75.chunk.js:2:441082)
    at w (Widget.4ea7db75.chunk.js:2:474090)
    at C (Widget.4ea7db75.chunk.js:2:474624)
    at Widget.4ea7db75.chunk.js:2:478058
    at l (Widget.4ea7db75.chunk.js:2:478173)
    at n (Widget.4ea7db75.chunk.js:2:477118)
```
